### ISSUE TITLE
SDK Crash when the device name containing arabic chars

### ISSUE THREAD

**Issue by ahmed7official** [Tap-Payments/goSellSDK-AndroidX#17]
This crash occurs when the mobile device name containing any arabic chars 

**Headers.kt line 434
okhttp3.Headers$Companion.checkValue**

```
Fatal Exception: java.lang.IllegalArgumentException
Unexpected char 0x627 at 157 in Application value: app_id=com.tech_world.romansia|requirer=SDK|requirer_version=3.11.2|requirer_os=Android|requirer_os_version=11|app_locale=ar|requirer_device_name=Galaxy A51 الخاص بـ محمد|requirer_device_type=samsung|requirer_device_model=SM-A515F|sdk_version=3.11.2|requirer_sim_network_name=STC|requirer_sim_country_iso=sa
```

```Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x627 at 157 in Application value: app_id=com.tech_world.romansia|requirer=SDK|requirer_version=3.11.2|requirer_os=Android|requirer_os_version=11|app_locale=ar|requirer_device_name=Galaxy A51 الخاص بـ محمد|requirer_device_type=samsung|requirer_device_model=SM-A515F|sdk_version=3.11.2|requirer_sim_network_name=STC|requirer_sim_country_iso=sa
       at okhttp3.Headers$Companion.checkValue(Headers.kt:434)
       at okhttp3.Headers$Companion.access$checkValue(Headers.kt:346)
       at okhttp3.Headers$Builder.add(Headers.kt:245)
       at okhttp3.Request$Builder.addHeader(Request.kt:210)
       at company.tap.gosellapi.internal.api.api_service.RetrofitHelper.lambda$getOkHttpClient$0(RetrofitHelper.java:89)
       at company.tap.gosellapi.internal.api.api_service.-$$Lambda$RetrofitHelper$ePrbZyNXyTCaPsWQOg6W7xGpDWE.intercept()
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by ahmed7official** [comment]
Fixed in v3.12.1
