### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by codelab-sahil** [Tap-Payments/goSellSDK-AndroidX#33]
Getting app crashed in payment page when user tapped on Payment Gateway.
Please check below logs for more details. 

```
          Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
       at company.tap.gosellapi.internal.activities.GoSellPaymentActivity.setGooglePayAvailable(GoSellPaymentActivity.java:1632)
       at company.tap.gosellapi.internal.activities.GoSellPaymentActivity.lambda$possiblyShowGooglePayButton$5$company-tap-gosellapi-internal-activities-GoSellPaymentActivity(GoSellPaymentActivity.java:1604)
       at company.tap.gosellapi.internal.activities.GoSellPaymentActivity$$ExternalSyntheticLambda4.onComplete(:4)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
```

> Brand: Samsung
> Model: Galaxy S9
> Orientation: Portrait
> Version:Android 10

Let me know if there is anything else required.

**Comment by MahmoudAbunaji92** [comment]
Same issue
